### ISSUE TITLE
How can I train the model?

### ISSUE THREAD

**Issue by jeongwonkwak** [Yao-Dou/LENS#11]
Hi there,

I have been exploring the `regression_metric_multi_ref.py` file in the repository and I'm interested in understanding the process of training a model using this script.

I noticed that there seems to be no explicit `training_step` defined in the `regression_metric_multi_ref.py` file. However, I might be overlooking something, and I would greatly appreciate it if you could shed some light on how the model is trained using this script.

Do you have any plans to release the code for training the Comet model, aside from the checkpoint model?

Best regards,

**Comment by mounicam** [comment]
Hello,

Currently, we are only releasing the checkpoint. To train a similar model, you can add the regression_metric_multi_ref.py file to the comet/models folder of the COMET repo and train using the instructions given in the COMET repo. Please let me know if you need any other questions.
