### ISSUE TITLE
Are the SARI implementations on Lens platform and github repo the same?

### ISSUE THREAD

**Issue by WuXuanxin** [Yao-Dou/LENS#14]
Hello, I've been using the Lens platform from http://nlprx.cc.gatech.edu:9015/ and noticed that the SARI score is calculated as an average of sentence-level scores. 

However, when I used the sari.py script from experiments/meta_evaluation/metrics, it yielded a different result. 

Could you please explain the SARI calculation method used on your platform?

**Comment by Yao-Dou** [comment]
The SARI on [Lens platform](http://nlprx.cc.gatech.edu:9015/ ) uses whitespace to separate tokens like: `grams = sent.lower().split(" ")`, I have changed it to `nltk.word_tokenize(sent.lower())` as the sari.py under the experiments/meta_evaluation/metrics.
